export const gradeLevels = [
  // ระบบไทย
  { value: 'อนุบาล 1', label: 'อนุบาล 1', category: 'ระบบไทย' },
  { value: 'อนุบาล 2', label: 'อนุบาล 2', category: 'ระบบไทย' },
  { value: 'อนุบาล 3', label: 'อนุบาล 3', category: 'ระบบไทย' },
  { value: 'ประถมศึกษาปีที่ 1', label: 'ประถมศึกษาปีที่ 1', category: 'ระบบไทย' },
  { value: 'ประถมศึกษาปีที่ 2', label: 'ประถมศึกษาปีที่ 2', category: 'ระบบไทย' },
  { value: 'ประถมศึกษาปีที่ 3', label: 'ประถมศึกษาปีที่ 3', category: 'ระบบไทย' },
  { value: 'ประถมศึกษาปีที่ 4', label: 'ประถมศึกษาปีที่ 4', category: 'ระบบไทย' },
  { value: 'ประถมศึกษาปีที่ 5', label: 'ประถมศึกษาปีที่ 5', category: 'ระบบไทย' },
  { value: 'ประถมศึกษาปีที่ 6', label: 'ประถมศึกษาปีที่ 6', category: 'ระบบไทย' },
  { value: 'มัธยมศึกษาปีที่ 1', label: 'มัธยมศึกษาปีที่ 1', category: 'ระบบไทย' },
  { value: 'มัธยมศึกษาปีที่ 2', label: 'มัธยมศึกษาปีที่ 2', category: 'ระบบไทย' },
  { value: 'มัธยมศึกษาปีที่ 3', label: 'มัธยมศึกษาปีที่ 3', category: 'ระบบไทย' },
  { value: 'มัธยมศึกษาปีที่ 4', label: 'มัธยมศึกษาปีที่ 4', category: 'ระบบไทย' },
  { value: 'มัธยมศึกษาปีที่ 5', label: 'มัธยมศึกษาปีที่ 5', category: 'ระบบไทย' },
  { value: 'มัธยมศึกษาปีที่ 6', label: 'มัธยมศึกษาปีที่ 6', category: 'ระบบไทย' },
  
  // International System
  { value: 'Nursery', label: 'Nursery', category: 'International' },
  { value: 'Pre-K', label: 'Pre-K', category: 'International' },
  { value: 'Kindergarten', label: 'Kindergarten', category: 'International' },
  { value: 'Grade 1', label: 'Grade 1', category: 'International' },
  { value: 'Grade 2', label: 'Grade 2', category: 'International' },
  { value: 'Grade 3', label: 'Grade 3', category: 'International' },
  { value: 'Grade 4', label: 'Grade 4', category: 'International' },
  { value: 'Grade 5', label: 'Grade 5', category: 'International' },
  { value: 'Grade 6', label: 'Grade 6', category: 'International' },
  { value: 'Grade 7', label: 'Grade 7', category: 'International' },
  { value: 'Grade 8', label: 'Grade 8', category: 'International' },
  { value: 'Grade 9', label: 'Grade 9', category: 'International' },
  { value: 'Grade 10', label: 'Grade 10', category: 'International' },
  { value: 'Grade 11', label: 'Grade 11', category: 'International' },
  { value: 'Grade 12', label: 'Grade 12', category: 'International' },
  
  // British System
  { value: 'Year 1', label: 'Year 1', category: 'British' },
  { value: 'Year 2', label: 'Year 2', category: 'British' },
  { value: 'Year 3', label: 'Year 3', category: 'British' },
  { value: 'Year 4', label: 'Year 4', category: 'British' },
  { value: 'Year 5', label: 'Year 5', category: 'British' },
  { value: 'Year 6', label: 'Year 6', category: 'British' },
  { value: 'Year 7', label: 'Year 7', category: 'British' },
  { value: 'Year 8', label: 'Year 8', category: 'British' },
  { value: 'Year 9', label: 'Year 9', category: 'British' },
  { value: 'Year 10', label: 'Year 10', category: 'British' },
  { value: 'Year 11', label: 'Year 11', category: 'British' },
  { value: 'Year 12', label: 'Year 12', category: 'British' },
  { value: 'Year 13', label: 'Year 13', category: 'British' },
  
  // Short forms that people might type
  { value: 'ป.1', label: 'ป.1 (ประถมศึกษาปีที่ 1)', category: 'ระบบไทย' },
  { value: 'ป.2', label: 'ป.2 (ประถมศึกษาปีที่ 2)', category: 'ระบบไทย' },
  { value: 'ป.3', label: 'ป.3 (ประถมศึกษาปีที่ 3)', category: 'ระบบไทย' },
  { value: 'ป.4', label: 'ป.4 (ประถมศึกษาปีที่ 4)', category: 'ระบบไทย' },
  { value: 'ป.5', label: 'ป.5 (ประถมศึกษาปีที่ 5)', category: 'ระบบไทย' },
  { value: 'ป.6', label: 'ป.6 (ประถมศึกษาปีที่ 6)', category: 'ระบบไทย' },
  { value: 'ม.1', label: 'ม.1 (มัธยมศึกษาปีที่ 1)', category: 'ระบบไทย' },
  { value: 'ม.2', label: 'ม.2 (มัธยมศึกษาปีที่ 2)', category: 'ระบบไทย' },
  { value: 'ม.3', label: 'ม.3 (มัธยมศึกษาปีที่ 3)', category: 'ระบบไทย' },
  { value: 'ม.4', label: 'ม.4 (มัธยมศึกษาปีที่ 4)', category: 'ระบบไทย' },
  { value: 'ม.5', label: 'ม.5 (มัธยมศึกษาปีที่ 5)', category: 'ระบบไทย' },
  { value: 'ม.6', label: 'ม.6 (มัธยมศึกษาปีที่ 6)', category: 'ระบบไทย' },
]